import localFont from "next/font/local";
import "./globals.css";
import LenisScroll from "@/components/lenis-scroll/LenisScroll";
import DropDown from "@/components/dropdown/DropDown";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <LenisScroll>
        
      <body
      >
        <DropDown />
        <div className="transition-container bg-black">
        {children}
        </div>
      </body>
      </LenisScroll>
    </html>
  );
}
